# Dockerfile

# set base image for postgres, from docker hub registry
# postgres bulleye - https://hub.docker.com/_/postgres
FROM postgres:15-bullseye

# # 
# COPY ./docker/development/postgres/maintenance /usr/development/bin/maintenance

# # 
# RUN chmod +x /usr/development/bin/maintenance/*

# # 
# RUN mv /usr/development/bin/maintenance/* /usr/local/bin \
#   && rmdir /usr/development/bin/maintenance